# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYflwrY5Q8k9u6ZOCbpO98muHPNjc0k4

Multi_Linear_Regression

Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"""Importing Data and Preprocessing"""

df = pd.read_csv("50_Startups.csv")
df.head(6)

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
display(x,y)

"""Encoding the categorical data"""

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
display(x)

"""Splitting Data into train and test sets"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
display(x_train,x_test,y_train,y_test)

"""Training the Multiple Linear Regression Model on the training set"""

lr = LinearRegression()
lr.fit(x_train,y_train)

"""Predicting the Test set results"""

y_predict = lr.predict(x_test)
np.set_printoptions(precision =2)
print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))